[package]
name = "rookmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustop = "1.1.2"
home = "0.5.3"
fs = "0.0.5"
pickledb = "0.5.1"